class AutogeneratedFolder:
    def __init__(self, terms) -> None:
        self.autogenerated_folder_name = "ansys.dita.generatedcommands"
        self.version = terms["ansys_internal_version"]
        self.base_url = f"https://ansyshelp.ansys.com/Views/Secured/corp/v{self.ans_version}/en/"
        self.cmd_base_url = f"{self.base_url}/ans_cmd/"

    @property
    def autogenerated_folder_name(self):
        return self.autogenerated_folder_name

    @property
    def version(self):
        return self.version

    @property
    def base_url(self):
        return self.base_url

    @property
    def cmd_base_url(self):
        return self.cmd_base_url

    @property
    def autogenerated_folder_name(self, folder_name):
        self.autogenerated_folder_name = folder_name

    @property
    def version(self, version_value):
        self.version = version_value
        self.base_url = f"https://ansyshelp.ansys.com/Views/Secured/corp/v{self.ans_version}/en/"

    @property
    def base_url(self, url):
        self.base_url = url
        self.cmd_base_url = f"{self.base_url}/ans_cmd/"

    @property
    def cmd_base_url(self, base_url):
        self.cmd_base_url = base_url
