# Copyright (c) 2023 ANSYS, Inc. All rights reserved.

from pydoc.xml2python.cli import main

from click.testing import CliRunner


def test_cli_main_group():
    runner = CliRunner()
    result = runner.invoke(main, ["--help"])
    assert result.exit_code == 0

    assert (
        """A Python wrapper to convert XML documentation into Python source code with"""
        in result.output
    )

    assert "package  Create a Python package from your XML documentation." in result.output
    assert "version  Display current version." in result.output


def test_cli_main_package_group():
    runner = CliRunner()
    result = runner.invoke(main, ["package", "--help"])
    assert result.exit_code == 0

    assert "Create a Python package from your XML documentation." in result.output
    assert (
        "-f, --func-path PATH  Path to the directory that contains the functions that"
        in result.output
    )
    assert (
        "-t, --targ-path PATH  Path to the directory where you want the autogenerated"
        in result.output
    )
    assert "-t, --targ-path PATH  Path to the directory where you want the autogenerated"
