"""This module contains the functions to format the generated docstrings with
`Black <black_>`_."""


def run_black(package_path, max_docstring_length):
    """Run `Black <black_>`_ on the autogenerated package."""
    exec(f"black {package_path}/src/pyconverter/generatedcommands -l {max_docstring_length}")