# check spelling, codestyle
name: GitHub CI

# run only on main branch.  This avoids duplicated actions on PRs
on:
  workflow_dispatch:
  schedule: # UTC at 0300
    - cron: "0 3 * * *"
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.9'
  PACKAGE_NAME: 'pydita-ast'
  PACKAGE_NAMESPACE: 'pydita.ast'
  DOCUMENTATION_CNAME: 'pydita-ast.docs.pyansys.com'
  RESET_PIP_CACHE: 0
  RESET_AUTOSUMMARY_CACHE: 0
  RESET_DOC_BUILD_CACHE: 0
  ON_CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  code-style:
    name: "Code style"
    runs-on: ubuntu-latest
    steps:
      - name: PyAnsys code style checks
        uses: pyansys/actions/code-style@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}


  doc-style:
    name: "Documentation Style Check"
    runs-on: ubuntu-latest
    steps:
      - name: PyAnsys documentation style checks
        uses: pyansys/actions/doc-style@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}


  smoke-tests:
    name: Build and Smoke tests (Linux)
    runs-on: ubuntu-latest
    needs: [code-style]
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Build wheelhouse and perform smoke test
        uses: pyansys/actions/build-wheelhouse@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          library-namespace: ${{ env.PACKAGE_NAMESPACE }}
          operating-system: ${{ runner.os }}
          python-version: ${{ matrix.python-version }}


  smoke-tests-macos-windows:
    name: Build and Smoke tests (macOS and Windows)
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    runs-on: ${{ matrix.os }}
    needs: [code-style]
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Build wheelhouse and perform smoke test
        uses: pyansys/actions/build-wheelhouse@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          library-namespace: ${{ env.PACKAGE_NAMESPACE }}
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}


  build-test:
    name: "Build and unit testing"
    runs-on: ubuntu-latest
    needs: [smoke-tests]

    steps:
      - name: "Install Git and checkout project"
        uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: "Install os packages"
        run: |
          sudo apt update
          sudo apt-get install pandoc

      - name: "Cache pip"
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: Python-v${{ env.RESET_PIP_CACHE }}-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            Python-v${{ env.RESET_PIP_CACHE }}-${{ runner.os }}
    
      # The token will expire in 2024.
      - name: "Checkout mapdl-cmd-doc repository"
        uses: actions/checkout@v3
        with:
          repository: pyansys/mapdl-cmd-doc
          ref: feat/pydita-ast-predined-format
          token: ${{ secrets.MAPDL_CMD_DOC_TOKEN }}
          path: mapdl-cmd-doc

      - name: "Unit testing requirements installation"  
        run: |
          python -m pip install .[tests]

      - name: "Unit testing"
        run: |
          pytest -v --durations=10 --maxfail=10 \
            --reruns 7 --reruns-delay 3 --ghdir ${{ github.workspace }}\
            --cov=pydita.ast --cov-report=xml:coverage.xml --cov-report=html\
            --cov-report term

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          name: coverage.xml
          flags: coverage

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage.xml
          path: ./coverage.xml


  doc-build:
    name: Documentation building
    runs-on: ubuntu-latest
    needs: [doc-style]
    steps:
        # This checkout is repeated later at the 'doc-build' action. This could be avoided by copything the sh file here, but introduces some code duplicity.
      - name: "Install Git and checkout project"
        uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: "Cache pip"
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: Python-v${{ env.RESET_PIP_CACHE }}-Linux-${{ env.MAIN_PYTHON_VERSION }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            Python-v${{ env.RESET_PIP_CACHE }}-Linux-${{ env.MAIN_PYTHON_VERSION }}
      
      - name: "Install pydita-ast"
        run: |
          pip install .
      
      - name: "Retrieve PyDita-AST version"
        run: |
          echo "PYDITA_VERSION=$(python -c 'from pydita.ast import __version__; print(__version__)')" >> $GITHUB_ENV
          echo "PyDita-AST version is: $(python -c 'from pydita.ast import __version__; print(__version__)')"
    
      - name: "Cache docs build directory"
        uses: actions/cache@v3
        with:
          path: doc/_build
          key: doc-build-v${{ env.RESET_DOC_BUILD_CACHE }}-${{ env.PYDITA_VERSION }}-${{ github.sha }}
          restore-keys: |
            doc-build-v${{ env.RESET_DOC_BUILD_CACHE }}-${{ env.PYDITA_VERSION }}

      - name: "Cache autosummary"
        uses: actions/cache@v3
        with:
          path: doc/source/**/_autosummary/*.rst
          key: autosummary-v${{ env.RESET_AUTOSUMMARY_CACHE }}-${{ env.PYDITA_VERSION }}-${{ github.sha }}
          restore-keys: |
            autosummary-v${{ env.RESET_AUTOSUMMARY_CACHE }}-${{ env.PYDITA_VERSION }}
    
      - name: "Install docs build requirements"
        run: |
          pip install .[doc]

      - name: "Run Ansys documentation building action"
        uses: pyansys/actions/doc-build@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          checkout: false
          skip-install: true
          sphinxopts: -j auto
          dependencies: "graphviz"


  auto-doc:
    name: Autogenerated documentation
    runs-on: ubuntu-latest
    needs: [build-test]
    steps:
        # This checkout is repeated later at the 'doc-build' action. This could be avoided by copything the sh file here, but introduces some code duplicity.
      - name: "Install Git and checkout project"
        uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: "Cache pip"
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: Python-v${{ env.RESET_PIP_CACHE }}-Linux-${{ env.MAIN_PYTHON_VERSION }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            Python-v${{ env.RESET_PIP_CACHE }}-Linux-${{ env.MAIN_PYTHON_VERSION }}
      
      # The token will expire in 2024.
      - name: "Checkout mapdl-cmd-doc repository"
        uses: actions/checkout@v3
        with:
          repository: pyansys/mapdl-cmd-doc
          ref: feat/pydita-ast-predined-format
          token: ${{ secrets.MAPDL_CMD_DOC_TOKEN }}
          path: mapdl-cmd-doc
      
      - name: "Install pydita-ast"
        run: |
          pip install .
      
      - name: "Create pydita-autogenerated doc"
        run: |
          python ./xml2rst.py -p ${{ github.workspace }}/mapdl-cmd-doc
      
      - name: Upload autogenerated doc artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./package


  auto-doc-build:
    name: Building autogenerated documentation
    runs-on: ubuntu-latest
    needs: [auto-doc]
    steps:
      - name: Download autogenerated documentation
        uses: actions/download-artifact@v3
        with:
          name: package
      
      - name: Test artifact download
        run: ls -R

      - name: Rearrangement folder
        run: |
          mv "./package/"* . && rm -rf "./package"

      - name: "Run Ansys documentation building action"
        uses: pyansys/actions/doc-build@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          checkout: false
          sphinxopts: -j auto


  package:
    name: Package library
    needs: [doc-build, auto-doc-build]
    runs-on: ubuntu-latest
    steps:
      - name: Build library source and wheel artifacts
        uses: pyansys/actions/build-library@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}


  doc-deploy-dev:
    name: "Deploy development documentation"
    # Deploy development only when merging to main
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [package]
    steps:
      - name: "Deploy the latest documentation"
        uses: pyansys/actions/doc-deploy-dev@v4
        with:
            cname: ${{ env.DOCUMENTATION_CNAME }}
            token: ${{ secrets.GITHUB_TOKEN }}


  release:
    name: "Release project to private PyPI and GitHub"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs:  [package, smoke-tests-macos-windows]
    runs-on: ubuntu-latest
    steps:
    - name: "Release to the private PyPI repository"
      uses: pyansys/actions/release-pypi-private@v4
      with:
        library-name: ${{ env.PACKAGE_NAME }}
        twine-username: "__token__"
        twine-token: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}

    # - name: "Release to the public PyPI repository"
    #   uses: pyansys/actions/release-pypi-public@v3
    #   with:
    #     library-name: "pydita-ast"
    #     twine-username: "__token__"
    #     twine-token: ${{ secrets.PYPI_TOKEN }}

    - name: "Release to GitHub"
      uses: pyansys/actions/release-github@v4
      with:
        library-name: ${{ env.PACKAGE_NAME }}


  doc-deploy-stable:
    name: "Deploy stable documentation"
    # Deploy release documentation when creating a new tag
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: "Deploy the stable documentation"
        uses: pyansys/actions/doc-deploy-stable@v4
        with:
            cname: ${{ env.DOCUMENTATION_CNAME }}
            token: ${{ secrets.GITHUB_TOKEN }}
            python-version: ${{ env.MAIN_PYTHON_VERSION }}
